### ISSUE TITLE
issues about the align 

### ISSUE THREAD

**Issue by jywu511** [DurrLab/C3VD#10]
Hi, thanks for publishing the good work!
When I want to align and render another shape "Sigmoid Colon", I download the "sampledata" at github, and download the 3D Model Files at https://durrlab.github.io/C3VD/, and replace the images, depth, pose, and 3D models.
However, the error is "what(): cannot parse materials ... ". It seems the 3D models at https://durrlab.github.io/C3VD/ is not compatible with the published code?
Looking forward to your reply and thanks again for sharing your work!

Best regards

**Comment by tbobrow1** [comment]
Hi @jywu511 - thanks for reporting this error. This is likely caused by the .obj file parser requiring a material file. The parser expects a separate material file to accompany the .obj, but the .obj files uploaded to the website do not include these. The program does not use any material/texture properties, so I will look into pushing an update that removes the need for a .mtl file to be included.

In the meantime, try downloading the sample data from the .README. This includes a .mtl file that you can paste into your directory. You will also need to open the sigmoid .obj file with a text editor and add the following line below the header - "mtllib ./model.mtl" - so that the parser knows which material file to link with the .obj. If you open the "model.obj" in the sample data directory, you will also see this line.

Let me know if this works, and I will try to get to pushing a correction for this shortly.

**Comment by jywu511** [comment]
@tbobrow1 Thank you very much for your quick response! I'll go and try it right away.

**Comment by jywu511** [comment]
Awesome! It works! Thank you very much!

**Comment by jywu511** [comment]
Hi, @tbobrow1, I discovered another issue. In the pose.txt file, time information is required. However, the pose.txt file available at https://durrlab.github.io/C3VD/ does not contain time information, which is causing alignment issues. Looking forward to your response. Thank you!

**Comment by tbobrow1** [comment]
The alignment window program is intended to initialize the position of the 3D model before registration and ground truth rendering. The pose.txt files on the dataset website are not intended to be input to these programs. They are outputs from the rendering program, which saves one *camera pose* per frame. The programs expect *robot poses* with time stamps (denoted as matrix A in the paper) sampled at a higher rate than the camera. The programs sample the robot pose log, then transform the robot poses to camera poses using the handeye matrices in the config file. The sample data linked in the README file is set up in this way. 

If you want to run sequences from the dataset website back through the programs, add timestamps to each line in pose.txt. The poses are sampled at the camera frame rate (29.97 fps). You'll also have to change the handeye matrices (Acal, Bcal, X) to identity matrices so that the handeye transformation results in outputs equal to inputs.

Let me know if this helps.

**Comment by jywu511** [comment]
Hi, @tbobrow1. Thanks for your reply!. I’ve downloaded the model and pose from https://durrlab.github.io/C3VD/ , and my goal is to render the diffuse image, or virtual image, using the code you provided. However, based on the pose I downloaded, the camera can’t currently locate to the colon, as shown in the picture. 
How should I solve this? Thank you very much!
![image](https://github.com/DurrLab/C3VD/assets/91044076/af6733b1-7f2d-4011-8053-bfca97bcd89c)

**Comment by tbobrow1** [comment]
@jywu511, are you using the model from the webpage or inside the .zip video directory? The models on the website are not registered to any specific scene, but the models within each .zip file have been registered and transformed.

**Comment by jywu511** [comment]
@tbobrow1 Hi, I have already replaced 'model.obj' with 'coverage_mesh.obj' from the zip file, but I am still unable to locate it correctly. In particular, I do not know how to set the parameters in the 'config.ini' file. Can you give more examples? Looking forward to your reply, thank you!

**Comment by tbobrow1** [comment]
Hi @jywu511 - the manuscript has a detailed explanation of all the variables, and the README lists what they are named in the config file. Here is a high-level synopsis of everything happening at each frame render:

1. The camera pose for the current frame is sampled by:
a. Sampling the robotic arm pose from the pose log for time = _poseStartTime_ + 29.97*CurrentFrameNumber . The sample is a linear interpolation of the two temporally neighboring poses in the text file.
b. The robotic arm pose is transformed into the camera pose using the handeye transform (equation 2 in the paper). If the text file contains camera poses instead of robotic arm poses, then you can set _Acal_,  _Bcal_, and _X_ to identity matrices so that the output of the handeye transform is equal to the input.
2.) The model pose is updated to  _modelTransform_. This transform is composed if three rotational elements (Roll,Pitch,Yaw) and three translational elements (tx,ty,tz).
3.) The frame is rendered at the current camera pose and model transform.

Looking at the GUI preview you uploaded, you have the _poseStartTime_ set to 12.02. It should be set to 0, because the first entry of the pose log should correspond with the first frame of the sequence. Additionally, all 6 of the model transform parameters should be set to 0, because the coverage_mesh.obj from the .zip file has already been transformed to the registered position. If you were trying to align the unregistered models from the webpage, then you would use the GUI to visually adjust the transform until the model is roughly at the current pose.

Let me know if it works after these two changes.

**Comment by jywu511** [comment]
@tbobrow1 It works!!! Thanks!!!
