### ISSUE TITLE
Meaning of camera calibration parameters

### ISSUE THREAD

**Issue by ZJJ2022415** [DurrLab/C3VD#2]
Excuse me, what are the parameters of camera a0, a2, a3, a4, e, f, g respectively?

Or what parameters do they correspond to in cy, cx, k1, k2, p1, p2, and p3?

**Comment by ZJJ2022415** [comment]
In addition, is there a parameter a1 missing in the folder cfhq190l_omnidirectional_params?

**Comment by tbobrow1** [comment]
The camera model that we utilized for this work is a non-linear spherical camera model by Scaramuzza et al that enables modeling of the entire colonoscope field of view. We define the camera model parameters and usage in our paper; the authors of the camera model also have a nice description on [their webpage](https://sites.google.com/site/scarabotix/ocamcalib-omnidirectional-camera-calibration-toolbox-for-matlab). Note that a1 is typically assumed to be 0 and is excluded from the model.

The parameters cy, cx, k1, k2, p1, p2, and p3 that you refer to come from the standard pinhole camera model. We opted not to use this model when generating the dataset, because a large portion of the outer field of view is not sampled. You can still use the pinhole camera model in application. These calibration parameters are fx: 802.319, fy: 801.885, cx: 668.286, 	cy: 547.733, k1: -0.42234, k2: 0.10654. On the dataset webpage, we also publish the checkerboard images so that you can calibrate for your desired model.

**Comment by ZJJ2022415** [comment]
> 

Thanks a lot!
