### ISSUE TITLE
Questions about the number of data sets

### ISSUE THREAD

**Issue by liuyeqi94** [DurrLab/C3VD#7]
Hello @tbobrow1，

Thanks to the author for providing such a comprehensive dataset, and I'm very much looking forward to your work. 

But I noticed that in the web page https://durrlab.github.io/C3VD/ , the file sigmoid_t1_a_under_review.zip has 800 frames after unzip instead of 700 as labeled on the page. Also, why does the number of different textures and parts vary a lot, plus there is no data for ascending colon What is the reason? 

Thank you again for your contribution and I am looking forward to your answer.

**Comment by tbobrow1** [comment]
Hi @liuyeqi94, I am glad that you are finding the data to be useful.

I just downloaded and checked the sigmoid_t1_a_under_review.zip file from the webpage and verified that it does have 700 frame sets in it. Do you mind redownloading and confirming that you also see 700 frame sets?

Regarding the variety of data, data recording and registration/rendering were completed in two separate phases. We eliminated redundant and unusable frames to maximize the data variation while minimizing the dataset size. This resulted in a mixed balance of textures and model segments.

We do not include any sequences for the ascending colon segment because the model does not include a flexure (or bend) to mask the external lab environment. Though, this segment is included in the simulated screening colonoscopy videos as part of the full colon model.

Let me know if I can be helpful in any other way as you use the dataset.

**Comment by liuyeqi94** [comment]
Hello @tbobrow1，Thank you for your prompt responses. 

I have redownloaded the file and can confirm that it  indeed contains 700 frames sets. I apologize for any confusion caused earlier.

Thank you for your explanation of the dataset. I look forward to your latest research.
